Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname="prueba"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 2
    end
end
